In [1]:
%cd ../
%load_ext autoreload
%autoreload 2

/Users/matthaei/Documents/code/python/bachelor-project

In [2]:
from src.weather_stations.weather_station_service import WeatherStationService
from src.measurements.measurement_service import MeasurementService
from src.calculation.calculation_service import CalculationService
from src.wind_turbines.wind_turbines_service import WindTurbinesService
from src.database.database_service import DatabaseService
from omegaconf import DictConfig, OmegaConf
from hydra import compose, initialize_config_dir
import os

In [3]:
# Initialize Hydra configuration
config_dir = os.path.abspath("./conf")

# Initialize Hydra with the config directory
with initialize_config_dir(config_dir=config_dir, version_base=None):
    cfg = compose(config_name="config")

In [4]:
database_service = DatabaseService(cfg)

In [5]:
weather_station_service = WeatherStationService(cfg, database_service)
weather_stations_df = weather_station_service.load_from_database()

2025-09-04 15:12:12.575 | INFO     | src.weather_stations.weather_station_data_provider:load_from_database:225 - Loaded 26 weather stations from database

In [6]:
wind_turbine_service = WindTurbinesService(cfg, database_service)
wind_turbines_df = wind_turbine_service.load_from_database()

2025-09-04 15:12:14.364 | INFO     | src.wind_turbines.wind_turbines_data_provider:load_from_database:181 - Loaded 4798 wind turbines from database

In [7]:
measurement_service = MeasurementService(cfg, database_service, weather_stations_df)

## Calculate the dataset

In [8]:
calculation_service = CalculationService(cfg, database_service, measurement_service, wind_turbines_df, weather_stations_df)

In [10]:
dataset = calculation_service.create_dataset()

2025-09-04 15:27:51.236 | INFO     | src.measurements.measurement_data_provider:load_measurements_from_database_for_datetime:200 - Loaded 17 measurements from database for datetime 2025-09-04 10:00:00
2025-09-04 15:27:51.261 | INFO     | src.calculation.calculation_service:create_dataset:56 - Wind speed: 3.3337169515461333, Wind direction: 232.32231256143137

In [25]:
dataset

,average_wind_direction,average_wind_speed,id,quality_level,record_date,station_id
0,200.0,3.0,935735,2,2025-09-04 10:00:00,164
1,230.0,2.5,298573,2,2025-09-04 10:00:00,96
2,250.0,3.4,1233308,2,2025-09-04 10:00:00,303
3,220.0,3.3,1531889,2,2025-09-04 10:00:00,427
4,230.0,2.9,1830470,2,2025-09-04 10:00:00,880
5,230.0,3.8,2129051,2,2025-09-04 10:00:00,1001
6,200.0,3.9,2427632,2,2025-09-04 10:00:00,1869
7,170.0,3.7,2726213,2,2025-09-04 10:00:00,2794
8,230.0,3.6,3024794,2,2025-09-04 10:00:00,2856
9,220.0,2.0,3323375,2,2025-09-04 10:00:00,3015
10,200.0,2.9,3621956,2,2025-09-04 10:00:00,3158
11,210.0,2.7,3920537,2,2025-09-04 10:00:00,3376
12,240.0,3.1,4219118,2,2025-09-04 10:00:00,3987
13,220.0,3.6,4517700,2,2025-09-04 10:00:00,5546
14,230.0,3.3,4815741,2,2025-09-04 10:00:00,5825
15,220.0,4.2,5114322,2,2025-09-04 10:00:00,6253

In [26]:
weather_stations_df

,end_date,height,is_active,latitude,longitude,name,start_date,state,weather_station_id
0,2025-09-03,50.0,True,52.9437,12.8518,Neuruppin-Alt Ruppin,2019-04-09,Brandenburg,96
1,2025-09-03,54.0,True,53.0316,13.9908,Angermünde,1908-05-17,Brandenburg,164
2,2025-09-03,55.0,True,52.0613,13.4997,Baruth,1993-09-06,Brandenburg,303
3,2025-09-03,46.0,True,52.3807,13.5306,Berlin,1957-01-01,Brandenburg,427
4,2025-09-03,69.0,True,51.7759,14.3168,Cottbus,1887-01-01,Brandenburg,880
5,2025-09-03,97.0,True,51.6451,13.5747,Doberlug-Kirchhain,1948-07-01,Brandenburg,1001
6,2025-09-03,56.0,True,53.3154,13.9339,Grünow,1973-01-01,Brandenburg,1869
7,2025-09-03,78.0,True,51.7657,13.1666,Holzdorf-Bernsdorf,2000-06-01,Brandenburg,2315
8,2025-09-03,128.0,True,51.5554,13.8845,Schipkau-Klettwitz,1996-07-01,Brandenburg,2627
9,2025-09-03,40.0,True,52.9362,12.4093,Kyritz,1945-05-01,Brandenburg,2794
10,2025-09-03,92.0,True,51.9173,13.0878,Langenlipsdorf,1993-06-01,Brandenburg,2856
11,2025-09-03,20.0,True,53.1007,11.4864,Lenzen/Elbe,1994-10-01,Brandenburg,2951
12,2025-09-03,98.0,True,52.2085,14.1180,Lindenberg,1906-04-01,Brandenburg,3015
13,2025-09-03,57.0,True,51.9267,13.8797,Lübben-Blumenfelde,1991-10-01,Brandenburg,3083
14,2025-09-03,12.0,True,52.5468,14.5453,Manschnow,1985-01-01,Brandenburg,3158
15,2025-09-03,64.0,True,52.5176,14.1232,Müncheberg,1937-01-01,Brandenburg,3376
16,2025-09-03,78.0,True,53.1020,13.0421,Stechlin-Menz,2004-10-01,Brandenburg,3509
17,2025-09-03,81.0,True,52.3812,13.0622,Potsdam,1893-01-01,Brandenburg,3987
18,2025-09-03,187.0,True,52.1206,12.4586,Wiesenburg,1967-04-01,Brandenburg,5546
19,2025-09-03,68.0,True,53.1864,12.4949,Wittstock-Rote Mühle,1994-03-01,Brandenburg,5643
20,2025-09-03,51.0,True,52.9664,13.3268,Zehdenick,1948-07-01,Brandenburg,5745
21,2025-09-03,41.0,True,52.6198,12.7867,Berge,1953-07-01,Brandenburg,5825
22,2025-09-03,39.0,True,52.0192,14.7254,Coschen,2000-02-01,Brandenburg,6170
23,2025-09-03,31.0,True,52.4228,12.5667,,2001-10-01,Brandenburg,6253
24,2025-09-03,36.0,True,52.3613,12.3867,Wusterwitz,2004-05-01,Brandenburg,6265
25,2025-09-03,83.0,True,52.7461,13.8427,Heckelberg,2006-12-01,Brandenburg,7389